"""add xG columns

Revision ID: fe31f9547069
Revises: 0001
Create Date: 2026-06-21 02:48:25.245219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fe31f9547069'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('matches_external_id_key'), 'matches', type_='unique')
    op.create_index(op.f('ix_matches_external_id'), 'matches', ['external_id'], unique=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_matches_external_id'), table_name='matches')
    op.create_unique_constraint(op.f('matches_external_id_key'), 'matches', ['external_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###